#Cows and Bulls
import random

#Generate 4 random integers
a = random.randint(0,9)
b = random.randint(0,9)
c = random.randint(0,9)
d = random.randint(0,9)
number = str(a)+str(b)+str(c)+str(d)
count = 1
numlist = [str(a), str(b), str(c), str(d)]
num = None

#Get user input
while num != number:

#This part resets the counter each time 
  cow = 0
  bull = 0
  userlist = []
  inp = input("Guess a 4 digit number:")
  try:
    numy = int(inp)
  except:
    print("Invalid entry")
    continue
  if numy > 9999:
    print("The number you entered is too large, try again")
    continue
  num = str(inp)
  for piece in num:
    userlist.append(piece)
  if len(userlist) < 4:
    print("Hey!")
    continue
#Run the list generated by user
  for usernum in userlist:
#For each digit from the user, analyse each digit from the randomly generated list
    for numnum in numlist:
      if (usernum == numnum and userlist.index(usernum) == numlist.index(numnum)):
        bull = bull + 1
        break
      elif usernum == numnum:
        cow = cow + 1
        break
#Both bull and cow need break operations to prevent the correct number from being compared to other numbers in the random list
  print ("Entry:"+num+", Cows = ",cow," Bulls = ", bull," Number of attempts:", count)
  count = count + 1
print ("You got it! The number is "+num)
    
