#Cows and Bulls
import random

#Generate 4 random integers
a = random.randint(0,9)
b = random.randint(0,9)
c = random.randint(0,9)
d = random.randint(0,9)
number = str(a)+str(b)+str(c)+str(d)
count = 1
num = None

#Get user input
while num != number:
#This part resets the counter each time 
  cow = 0
  bull = 0
  m = 0
  inp = input("Guess a 4 digit number:")
  try:
    numy = int(inp)
  except:
    print("Invalid entry")
    continue
  if numy > 9999:
    print("The number you entered is too large, try again")
    continue
  num = str(inp)
  if len(num) < 4:
    print("Hey!")
    continue
#Run the list generated by user
  for usernum in num:
    n = 0
    for numnum in number:
      if usernum == numnum:
        if num[m] == number[n]:
          bull = bull + 1
          break
        else:
          cow = cow + 1
          break
      n += 1
    m += 1
#Both bull and cow need break operations to prevent the correct number from being compared to other numbers in the random list
  print ("Entry: "+num+", Cows = ",cow," Bulls = ", bull," Number of attempts:", count)
  count = count + 1
print ("You got it! The number is "+num)
    
